name: 'Code Scanning'

on:
  schedule:
    - cron: 0 23 * * 1
  push:
    branches:
    - dev
    - master
    - V6
  pull_request:
    branches:
    - dev
    - master
    - V6

env:
  TGS_DOTNET_VERSION: 8.0.x

concurrency:
  group: "code-scanning-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  analyze:
    name: Code Scanning
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    if: ${{ vars.TGS_ENABLE_CODE_QL }} == 'true'
    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '${{ env.TGS_DOTNET_VERSION }}.x'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Build
      run: dotnet build -c ReleaseNoWindows

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:csharp"
