name: 'Code Scanning'

on:
  schedule:
    - cron: 0 23 * * 1
  push:
    branches:
    - dev
    - master
  pull_request:
    branches:
    - dev
    - master

concurrency:
  group: "code-scanning-${{ github.head_ref || github.run_id }}-${{ github.event_name }}"
  cancel-in-progress: true

jobs:
  analyze:
    name: Code Scanning
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    if: ${{ vars.TGS_ENABLE_CODE_QL }} == 'true'
    steps:
    - name: Install Node 12.X
      uses: actions/setup-node@v3
      with:
        node-version: 12.x

    - name: Upgrade NPM
      run: npm install -g npm

    - name: Checkout
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: csharp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:csharp"
